apiVersion: v1
kind: Template
metadata:
  name: fabric8-tenant-che-migration-configmap-template
objects:
- apiVersion: v1
  data:
    migration: 'singleTenantToMultiTenant'
    che-multitenant-server: ${CHE_MULTITENANT_SERVER}
    identity-id: theIdentity
    osio-token: ${OSIO_TOKEN}
    request-id: ${REQUEST_ID}
    cleanup-single-tenant: ${CLEANUP_SINGLE_TENANT}
  kind: ConfigMap
  metadata:
    name: migration
    namespace: dfestal-che
parameters:
- description: Osio Token
  name: OSIO_TOKEN
  value: ""
- description: If we should cleanup single tenant resources after single-tenant to multi-tenant migration
  name: CLEANUP_SINGLE_TENANT
  value: "true"
- description: Request ID
  name: REQUEST_ID
  value: "theRequestId"
- description: Base URL of the multi-tenant Che server
  name: CHE_MULTITENANT_SERVER
  value: 'https://che.glusterpoc37aws.devshift.net'
